services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snapjournal_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - snapnet

  webserver:
    image: nginx:latest
    container_name: snapjournal_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - snapnet

  db:
    image: mysql:8.0
    container_name: snapjournal_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diaryjournal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - snapnet

networks:
  snapnet:

volumes:
  dbdata:
